### ISSUE TITLE
Consider expanding the cookie's path

### ISSUE THREAD

**Issue by craigcook** [mozmeao/trafficcop#34]
Currently when Traffic Cop sets its cookie the path is `undefined` which defaults to the current page URL. This means that cookie can only be read again by the same page that set it. 

There may be some scenarios when we want to check for a Traffic Cop cookie from a different page, to determine if someone was enrolled in a previous experiment elsewhere, but that isn't currently possible because of the default restricted path.

If we make the cookie path an optional parameter in Traffic Cop, we could allow its cookie to be read by other pages on the same domain. It should still default to `undefined` unless specified.

**Comment by alexgibson** [comment]
Closing as wontfix, since TC no longer uses cookies
