### ISSUE TITLE
Remove the Mozilla JS namespace when publishing

### ISSUE THREAD

**Issue by alexgibson** [mozmeao/trafficcop#4]
Now that we're publishing Traffic Cop in UMD format, we can probably remove the `Mozilla.*` name space. So instead of doing:

```javascript
require('@mozmeao/trafficcop');

const cop = new window.Mozilla.TrafficCop();`
```

We could instead do:

```javascript
const TrafficCop = require('@mozmeao/trafficcop');

const cop = new TrafficCop();
```

Or alternatively:

```javascript
import TrafficCop from '@mozmeao/trafficcop';
 
const cop = new TrafficCop();
```

And for sites without a build system:

```javaScript
const cop = new window.TrafficCop();
```

It would also be good to include how to install Traffic Cop in the project readme, together with the different ways to initialise it.

**Comment by alexgibson** [comment]
Thought this might be a nice semantic improvement? 

/cc @nathan-barrett @reemhamz

**Comment by nathan-barrett** [comment]
I also noticed an issue in the package's package.josn - the issues property points to protocol (oops!)

**Comment by alexgibson** [comment]
Think I'm going to take a look at unwinding this one.

**Comment by reemhamz** [comment]
Just caught wind of this but I approve this improvement. Less things to remember and less error prone when writing more complex JavaScript

**Comment by alexgibson** [comment]
PR to remove the `Mozilla` JS namespace: https://github.com/mozmeao/trafficcop/pull/5
