### ISSUE TITLE
Remove use of cookies

### ISSUE THREAD

**Issue by alexgibson** [mozmeao/trafficcop#56]
As part of our upcoming privacy consent work, all non-essential cookies will now require explicit consent to be granted before they can be set. This presents us with the following options for Traffic Cop (TC):

1. Only initialize experiments if explicit consent has previously been given.
2. Remove reliance on cookies from TC entirely, so it can run independently of consent.

I'm proposing we do 2) because:

1. TC redirects happen before page load, and therefore before consent is likely to have been given previously. Doing 1) will likely result in a considerably number of people who DO give consent, but never actually enter into an experiment because they don't make a repeat visit.
2. TC doesn't actually record any experiment specific data itself. Instead it relies on our regular analytics tools which will require consent separately. 
3. TC does set a cookie to remember which variation a visitor has previously seen, and additionally sets another cookie to record the original referrer (if present).

The cookies TC does set are certainly useful, but given our constraints I think we're likely to get more overall experiment data if we drop them, so TC can run independently of any consent dialog?

The downside is a visitor might see a different experiment variation if they make a return visit during the experiment window. We would also lose the original referrer in our data during the course of an experiment running.

**Comment by alexgibson** [comment]
Additional note: we also need to remove the DNT check from Traffic Cop, since this will no longer be used for consent.

**Comment by nathan-barrett** [comment]
Another vote for option 2: `Remove reliance on cookies from TC entirely, so it can run independently of consent.`

**Comment by stephaniehobson** [comment]
Another vote for 2 if/when we need to make changes.
